`IntoPyDict::into_py_dict` is now fallible due to `IntoPyObject` migration.