* Removed the bindings for the private function `_PyErr_ChainExceptions`.
